### ISSUE TITLE
[Bug] Item Dropping Upon Destruction in Creative

### ISSUE THREAD

**Issue by QuantumTraverse** [igentuman/nc-steam-additions#20]
While in creative mode, destroying the heat exchanger sometimes causes it to drop as an item. I have not seen this bug on any of the other blocks, just the exchanger.

**Comment by QuantumTraverse** [comment]
Actually, it looks like the steam turbine does too. It appears to be from the fact that both of these blocks are bigger than 1 block. When one clicks to smash on the upper block part, that is what causes the item to drop in creative

**Comment by QuantumTraverse** [comment]
Also, if you use pick block on the upper portion, it gives you a weird invisible slab block

**Comment by igentuman** [comment]
it is a boundary block
