### ISSUE TITLE
 NuclearCraft Steam Additions does not run properly on the Sponge Server

### ISSUE THREAD

**Issue by FnTlv** [igentuman/nc-steam-additions#23]
Running Environment:
    - Minecraft: 1.12.2
    - SpongeAPI: 7.4.0-5ea6215
    - Sponge: 1.12.2-7.4.7
    - SpongeForge: 1.12.2-2838-7.4.7
    - Minecraft Forge: 14.23.5.2860
Description:
    When I right click on the machine, the gui does not open.
Report(logs):
    https://pastes.dev/gbWu3zQFeL
    https://pastes.dev/7IfDy2y0Nw

**Comment by igentuman** [comment]
You can try automatic build https://github.com/igentuman/nc-steam-additions/actions/runs/4254384579
